name: dorlink
runtime: yaml
description: Example of deploying static website
resources:
  web:
    type: "aws-static-website:index:Website"
    properties:
      sitePath: "../my-website/build"
outputs:
  websiteURL: ${web.websiteURL}
