version: 0.2

files:
  - source: .
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies      
      runas: root
    - location: scripts/start_server     
      runas: root